# Generated by Django 5.0.2 on 2024-03-19 09:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctor', '0002_alter_designation_name_alter_designation_slug_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='availabe_time',
            new_name='available_time',
        ),
    ]
